// ignore_for_file: file_names

import 'package:get/get.dart';

class RulesRegulationController extends GetxController {
  List rules = [
    "All Super Home resident/customer must abide by the rules and regulations of the Super Home as may be framed from time to time.",
    "Every resident/customer must be paid his/her Security deposit according to our policy during booking or before shifting to the Super Home; Every resident/ customer must Collect his/her Membership card and booking money receipt from the consultancy Zone (Lobby) during the time of check-in.",
    "Security Deposit is fully refundable at the time of leaving from Hostel subject to certain conditions.",
    "You have to bring your NID/Smart Card/Passport/Birth Certificate along with original copy of Institutional ID or Employee ID during booking and shifting. Foreigners have to show their passport, including valid visa page. If any resident/customer below age of 18 years, wants to stay then have to provide the guardian’s NID copy.",
    "The rent will be counted from the shifting date which is provided by the customer/ hostel residents unless he/she informs the authority.",
    "If a guardian books a seat for a student, then he/she must give the authority to the Super Home management regarding the cancelation and handling the Security Deposit.",
    "Resident/Customer has to fill up the Police verification Form properly with accurate information and authentic emergency contact number.",
    "Security Deposit will not be adjusted with the rent of last month and no consideration will be taken into notice in this regard.",
    "There is one time slot in a month. Have to be submitted an application physically from 1st to 10th days of month for the cancellation of seat or package shifting, then authority will take further steps according to the policy.",
    "Electricity bill is excluded. Every month electricity bill has to be adjusted at the end of the month.",
    "Cancellation paper work must be completed 1(one) day prior to your departure with the help of Branch management.",
    "In first month Super Hostel’s resident/customer can’t cancel the seat, the procedure of the cancelation will start in next month.",
    "Hostel’s resident/customer should always keep their room neat and tidy and use the dustbin properly.",
    "Hostel’s resident/customer must use the washroom and flash properly so that other resident/customer can use it without any worries.",
    "Maintain dining schedule as per the rules and timing, please use the dining room for your meal, No resident/customer is allowed to take his/her meal outside from dining area.",
    "Every resident/customer will collect his/her locker keys, led light, laundry bag etc. from branch office at the time of checking into the Hostel and do not abuse those.",
    "Hostel premise is completely a non-smoking zone, consumption of any alcoholic beverages and gambling is strictly prohibited and any violation of such rule will be viewed as serious offence under laws of Bangladesh; offender will be handed over to the legal authority of Bangladesh and also security deposit money of concern resident/customer will be seized.",
    "Political activities as well as grouping are hardly restricted amongst the hostel residents/customers in the Hostel premises; if found, membership will be cancelled instantly and get him/her out from the Hostel right that moment or handed to the legal authority of Bangladesh.",
    "Carrying illegal substances such as drugs, explosives substances etc. in the hostel premises is forbidden and hostel resident/customer shall not use the same for doing any unlawful activities. Any kind of anti-government or anti-social activities will not be tolerated in any circumstances.",
    "Betting, making turbulence in the hostel premises, making noise and loudly talking or singing is highly prohibited and any activities regarding hampering the harmony of the neighborhood are strictly prohibited; Hostel authority reserves all rights to take any kind of decisions & legal actions when such situation arises.",
    "Playing loud musical game or making loud noise is prohibited; maintain personal conversation over cell phone with discreetly; also you are expected to open and close the door with proper manner.",
    "Hostel resident/customer is not allowed to display any obscene posters or calendars, wall writing etc. in the room or anywhere of the Hostel premises.",
    "Hostel residents/customers are supposed to take care of themselves. If Hostel resident/customer is suffering from any contagious disease, must have to leave the Hostel premises for medical treatment and unless the Hostel resident/customer is fully recovered would not be allowed to enter or stay in the Hostel premises for the safety and wellbeing of other Hostel residents/customers.",
    "Hostel resident/customer do not lock room or main door as according to the directions of DMP authority; they reserve the rights to check customer’s personal belongings randomly at any time.",
    "The Hostel customer/resident themselves are personally responsible to safeguard their belongings against any theft of laptop, mobile phone, computer, purse, calculator, wristwatch, wallet or any other valuable item but every case of theft should be reported promptly to the hostel administration so that proper steps could be taken against the guilty person.",
    "If anyone loses the locker key, it will be replaced to him/her after payment of BDT 500/- (for each key). For each laundry bag replacement cost is BDT 200/- and for each Bed Light & USB converter replacement cost are BDT 300/-.",
    "Guests are allowed only in lobby of the hostel but cannot stay in here or not allowed to visit in the room. Female guests are NOT allowed inside the male hostel and male guests are NOT allowed inside the female hostel; however, for meeting & greetings they can use only downstairs lobby.",
    "Hostel resident/customer should co-operate in carrying out maintenance work and vacate him/her rooms completely when the Hostel authority requires the rooms for maintenance purpose. On such occasions, the authority will try to provide him/her alternate accommodation. If any maintenance work is to be carried out when the room is under occupation, it is the occupant’s responsibility to make the room available for the same time.",
    "The Authority reserves the right to cancel the seat of any Hostel resident/customer at any time",
    "The Authority reserves the right to increase rent in a reasonable manner.",
    "No Hostel resident/customer is allowed to change his seat without prior permission of Branch Management.",
    "Every Hostel resident/customer must inform the Hostel Authority if he/she is staying outside of hostel overnight for their own safety.",
    "To carry or keep Fire Arms or any other Arms and Knife or as like other sharp things are strictly prohibited for Hostel resident/customer in Hostel Premises.",
    "For changing seat, first month have to stay and in second month within 1st to 5th day of that month have to apply in the consultancy zone by paying BDT 500, then Authority will check availability of desire seat and will take necessary steps for this.",
    "For parking bike, monthly BDT 500/- will be paid by bike holder for each bike and bike holder has to provide blue book copy and maintain the parking rules. This fee has to pay with monthly rent.",
    "Hostel Authority highly restricted for any kinds of personal electrical belonging used i.e. Auto-Heat water Machine, Iron Machine, Rice Cooker and etc. in Hostel Premises.",
    "Indulging in physical fight/quarrel/bout/teasing/using offensive or undermining language/non-observance of Hostel rules is strictly prohibited and every Hostel resident/customer must show respect and behave with modesty with the fellow Hostel residents/customers.",
    "You the Hostel resident/customer DO NOT have any authority to take any action inside the Hostel premises regarding any issues or circumstances. And for these, please contact to the Branch management immediately.",
    "For clothes washing service, Hostel resident/customer must use the laundry bag. Daily Limit is 1 set of clothes per day.",
    "Dining time need to maintain, only in lunch time we keep meal till 6 PM only for some students and for some job holders who are coming from their work area.",
    "If any Hostel resident/customer wishes to be away from the Hostel during the weekend, holidays or any other time, he/she has to notify Hostel Authority.",
    "Hostel resident/customer will use all the electronic goods i.e. AC, hair dryer, shoe-polisher etc. with proper safety & care. Resident/customer will be responsible for any damages done by him/her and have to pay compensation for that.",
    "Before leaving the Hostel please return all the key of lockers, LED lamp, laundry bag, membership card MR copy to the Branch Office and collect your clearance to complete your check out process; If lost or damaged any above have to pay the compensation before leave.",
    "No pet animals are allowed in the Hostel premise. Any mattress, table, shelf or any kinds of pots etc. are restricted.",
    "One resident/customer has one finger prints to enter into Hostel. Register your name at the time of late night entry or exit. Please, co-operate with the security during the entry and exit time on daily basis.",
    "Monthly rent is payable in advance within 10th day of each month. From 11th day of this month fine will be imposed BDT 100/-day for late payment of monthly rent and no consideration will be shown in this regard.",
    "Hostel Authority reserves all the exclusive right regarding continuation of stay of a resident/customer in the Hostel premises as well as in liberty to make any kind of decision and holds the right to change or alter the policy at any time.",
    "Room members can only enter their own room. After 11 PM no gossiping is allowed inside the room even in reading room.",
    "If any of the above mentioned terms & conditions need to be clarified to our customer or any one, the Neways International Company Ltd. reserves the right to clarify the same to them."
  ];
}
